mcp:
  servers:
    playwright:
      command: "npx"
      args: ["-y", "@playwright/mcp@latest"]
    brave_websearch:
      command: "npx"
      args: [ "-y", "@modelcontextprotocol/server-brave-search" ]
      env:
        BRAVE_API_KEY: "<KEY>"
